### ISSUE TITLE
Add support for Shared Drive

### ISSUE THREAD

**Issue by Oxalin** [buttercup/googledrive-client#15]
We have been using Buttercup at work individually and for a common shared vault. This latter was located in a shared folder until recently, which was working just fine. However, the shared folder has been replaced recently by a Shared Drive. From what I can see, Buttercup doesn't support Shared Drive. The Drive API does support it (https://developers.google.com/drive/api/v3/enable-shareddrives)

So it would be nice to add this support.

**Comment by perry-mitchell** [comment]
I'd accept a PR for this, given that the existing logic doesn't need to change per se (existing implementations won't break).

**Comment by perry-mitchell** [comment]
Fixed by #24
